In [1]:
import torch

In [2]:
torch.tensor([[1,2], [3,4]])

tensor([[1, 2],
        [3, 4]])

In [6]:
torch.tensor([[1,2], [3,4]], device="mps")

tensor([[1, 2],
        [3, 4]], device='mps:0')

In [7]:
torch.tensor([[1,2], [3,4]], dtype=torch.float64)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [8]:
temp = torch.tensor([[1,2], [3,4]])
temp.numpy()

array([[1, 2],
       [3, 4]])

In [9]:
temp = torch.tensor([[1,2], [3,4]], device="mps")

In [10]:
temp.to("cpu").numpy()

array([[1, 2],
       [3, 4]])

In [23]:
temp = torch.FloatTensor([1,2,3,4,5,6,7])

In [24]:
temp[0]

tensor(1.)

In [25]:
temp[6]

tensor(7.)

In [26]:
temp[7]

IndexError: index 7 is out of bounds for dimension 0 with size 7

In [27]:
temp[2:5]

tensor([3., 4., 5.])

In [28]:
temp[3:]

tensor([4., 5., 6., 7.])

In [29]:
v = torch.tensor([1,2,3])
w = torch.tensor([3,4,6])

In [30]:
v - w

tensor([-2, -2, -3])

In [31]:
temp = torch.tensor([[1,2], [3,4]])

In [32]:
temp

tensor([[1, 2],
        [3, 4]])

In [33]:
temp.shape

torch.Size([2, 2])

In [34]:
temp.view(4,1)

tensor([[1],
        [2],
        [3],
        [4]])

In [35]:
temp.view(-1)

tensor([1, 2, 3, 4])

In [37]:
temp.view(1,-1)

tensor([[1, 2, 3, 4]])

In [38]:
temp.view(-1, 1)

tensor([[1],
        [2],
        [3],
        [4]])